# Generated by Django 2.2.5 on 2019-09-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
    ]
