# Generated by Django 2.2.5 on 2019-09-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190923_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=48),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(to='app1.Product'),
        ),
    ]
